Repository Zilliqa/staking-contract, pull requests merged in 2020-09, with the labels that each got.

#75 fix(ssn): use proxyaddr field, not initial contract parameter
  contracts/ssnlist.scilla
Labels: audit

#82 fix: sub delegator's reward from total rewards, finish comments
  contracts/proxy.scilla
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: bug

#87 fix: remove wrong code
  contracts/ssnlist.scilla
Labels: bug

#93 fix/rewardscalculation
  contracts/gzil.scilla
  contracts/proxy.scilla
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: bug

#167 audit 6.5
  contracts/gzil.scilla
Labels: audit, merge ready

#133 audit 6.7
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit, merge ready

#148 audit 6.22
  contracts/multisig_wallet.scilla
Labels: audit, merge ready

#151 audit 6.23,6.24
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit, merge ready

#153 audit 6.26,6.28
  contracts/README.md
Labels: audit, merge ready

#156 audit 6.27,6.29
  contracts/README.md
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit, merge ready

#163 audit 6.30,6.31,6.32
  contracts/gzil.scilla
  contracts/multisig_wallet.scilla
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit, merge ready

#146 audit 6.21
  contracts/gzil.scilla
Labels: audit, merge ready

#134 audit 6.6,6.8,6.10,6.11,6.12
  contracts/README.md
  contracts/multisig_wallet.scilla
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit, merge ready

#129 audit 6.1
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit, merge ready

#164 audit 6.17
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit, merge ready

#170 fix: issue 168 and 8.3
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit

#173 audit 6.2
  contracts/README.md
  contracts/proxy.scilla
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit, merge ready

#178 fix: 6.9
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit, merge ready

#175 fix: remove RemoveSSN. audit 6.4, 6.16, 7.2
  contracts/README.md
  contracts/multisig_wallet.scilla
  contracts/proxy.scilla
  contracts/ssnlist.scilla
Labels: audit, merge ready

#176 audit 6.18
  contracts/README.md
Labels: audit, merge ready

#130 audit 6.3
  contracts/ssnlist.scilla
  tests/ssnlist.scilla
Labels: audit
